#!/bin/sh
#
# create helper protocol for konqueror to send klicks to the klik script
#

FLL_KLIK_KDE_ENABLE="Y"

[ -z "$KDEHOME" ] && [ -d "$HOME/.kde" ] && KDEHOME="$HOME/.kde"

[ -e /etc/klik.conf ] && . /etc/klik.conf
[ -e $HOME/.klik.conf ] && . $HOME/.klik.conf

[ -z "$KDEHOME" ] && exit

if [ "$FLL_KLIK_KDE_ENABLE" = "Y" ]; then

cat > $KDEHOME/share/services/klik.protocol <<EOF
# klik 0.2
# helper protocol for konqueror to send klicks to the klik script
# by probono
[Protocol]
exec=klik '%u'
protocol=klik
input=none
output=none
helper=true
listing=false
reading=false
writing=false
makedir=false
deleting=false
icon=package
Description=klik
EOF

#
# create $KDEHOME/share/applnk/klik
#

mkdir -p  $KDEHOME/share/applnk/klik

cat > $KDEHOME/share/applnk/klik/.directory <<EOF
[Desktop Entry]
Encoding=UTF-8
Name=Applications (installed by klik)
Name[de]=Programme (installiert mit klik)
Icon=rebuild
#package_applications
EOF

#
# link to the store
#

cat > $KDEHOME/share/applnk/klik/klik.desktop <<EOF
[Desktop Entry]
Encoding=UTF-8
Exec=konqueror http://klik.atekon.de?from=profile
Icon=package_network
Name=Install more software...
Name[de]=Weitere Software installieren...
EOF

mkdir -p $KDEHOME/share/mimelnk/all
cat > $KDEHOME/share/mimelnk/all/cmg.desktop <<\EOF
[Desktop Entry]
Comment=
Hidden=false
Icon=view_remove
MimeType=all/cmg
Patterns=*.cmg
Type=MimeType
EOF

mkdir -p $KDEHOME/share/applnk/.hidden
cat > $KDEHOME/share/applnk/.hidden/AppRun.desktop<<\EOF
[Desktop Entry]
Comment=
Exec=klik-run %U
Icon=view_remove
InitialPreference=2
MimeType=all/cmg;Application
Name=
ServiceTypes=
Terminal=false
Type=Application
EOF

kbuildsycoca 2>/dev/null

fi
