#!/bin/sh
mkdir -p $HOME/.local/share/mime/packages/
cat > $HOME/.local/share/mime/packages/Override.xml <<\EkOF
<?xml version="1.0" ?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info"><mime-type type="application/cmg"><glob pattern="*.cmg"/><comment>Compressed Application Image</comment></mime-type></mime-info>
EkOF

update-mime-database ~/.local/share/mime/

mkdir -p ~/.choice/MIME-types/
ln -sf /usr/bin/klik-run $HOME/.choice/MIME-types/application_cmg
