#!/bin/sh
CONFIGFILE=/etc/klik.conf
set -e
. /usr/share/debconf/confmodule

if [ ! -e $CONFIGFILE ]; then
  echo "#Config file for klik" > $CONFIGFILE
  echo "FLL_KLIK_FSTAB_ENABLE=" >> $CONFIGFILE
  echo "FLL_KLIK_MOUNT_GROUP=" >> $CONFIGFILE
  echo "FLL_KLIK_MOUNT_USERS=" >> $CONFIGFILE
fi

db_get fll/klik/rootsetup
FLL_KLIK_FSTAB_ENABLE="$RET"
db_get fll/klik/klikgroup
FLL_KLIK_MOUNT_GROUP="$RET"
db_get fll/klik/klikusers
FLL_KLIK_MOUNT_USERS="$RET"

test -z "$FLL_KLIK_FSTAB_ENABLE" || grep -Eq '^ *FLL_KLIK_FSTAB_ENABLE=' $CONFIGFILE || echo "FLL_KLIK_FSTAB_ENABLE=">>$CONFIGFILE
test -z "$FLL_KLIK_MOUNT_GROUP" || grep -Eq '^ *FLL_KLIK_MOUNT_GROUP=' $CONFIGFILE || echo "FLL_KLIK_MOUNT_GROUP=">>$CONFIGFILE
test -z "$FLL_KLIK_MOUNT_USERS" || grep -Eq '^ *FLL_KLIK_MOUNT_USERS=' $CONFIGFILE || echo "FLL_KLIK_MOUNT_USERS=">>$CONFIGFILE

sed -e "s/^ *FLL_KLIK_FSTAB_ENABLE=.*/FLL_KLIK_FSTAB_ENABLE=\"$FLL_KLIK_FSTAB_ENABLE\"/" -e "s/^ *FLL_KLIK_MOUNT_GROUP=.*/FLL_KLIK_MOUNT_GROUP=\"$FLL_KLIK_MOUNT_GROUP\"/" -e "s/^ *FLL_KLIK_MOUNT_USERS=.*/FLL_KLIK_MOUNT_USERS=\"$FLL_KLIK_MOUNT_USERS\"/" < $CONFIGFILE > $CONFIGFILE.tmp
mv -f $CONFIGFILE.tmp $CONFIGFILE

klik-root-setup
